### ISSUE TITLE
Macではrealpathコマンドがないので動作しない

### ISSUE THREAD

**Issue by yonchu** [pasberth/promptway#1]
最近使い始めた者で、とても気に入りました。

ですが、Macでは`realpath`コマンドが存在しないため動作しないようです。
(`promptway`と`pathf`いずれもrealpathコマンドを使用しています)

Macでは`gnuutils`をインストールすることで`grealpath`コマンドが使用出来るので、そちらでも動作するようにして頂けると助かります。
(`grealpath`を`realpath`としてシンボリックリンクを貼るという方法もありますが…)

良ければご検討願います。

**Comment by pasberth** [comment]
ありがとうございます。対応してみました

**Comment by yonchu** [comment]
確認しました。
素早い対応ありがとうございます。

これから便利に使わせて頂こうと思います。:satisfied:
