### ISSUE TITLE
名前付きディレクトリに対応したい

### ISSUE THREAD

**Issue by yonchu** [pasberth/promptway#19]
`PROMPT` に `%~` を指定すると名前付きディレクトリも変換してくれるので、promptwayでも対応したいです。

自分で実装しようと思ったんですが、思いのほか難しかったのでひとまずチケット化しときます。
良い案があれば、伺いたいです。

名前付きディレクトリは以下の方法で変換可能です。

``` sh
if is-at-least 4.3.11; then
  dir=${(D)dir}
fi
```

以下実行イメージ

``` console
$ hash -d hoge=/path/to/hoge
$ hash -d piyo=/path/to/hoge/fuga/piyo

$ cd /path/to/hoge
# 表示パス: ~hoge
#          ^^^^^
#         current

$ cd/path/to/hoge/fuga/piyo
# 表示パス: ~hoge/fuga/piyo
#          ^^^^       ^^^^
#        backward    current

$ cd/path/to/hoge/fuga
# 表示パス: ~hoge/fuga/piyo
#                ^^^^ ^^^^
#             current backward
```

よろしくお願いします。

**Comment by pasberth** [comment]
実装してみました。試してみてくださいな

ほんとうはテストしてもらってからマージしようと思ったのですが まちがって master に push してしまいました…
少々不安なところもなきにしもあらず なので、もしバグがあって救出不可能なようなら
もとに戻すかも(?)

**Comment by yonchu** [comment]
おおー！
試してみました。問題ないと思います。:thumbsup:

ありがとうございます。
