### ISSUE TITLE
起動時にパスが設定されない

### ISSUE THREAD

**Issue by yonchu** [pasberth/promptway#2]
READMEの漏れかと思いますが、Usageに書かれてある設定だけでは、`_update_prompt_way`が`chpwd`契機でしか呼ばれないため、起動時にパスが設定されません。

おそらく`_update_prompt_way`はsource時にも呼ばれることを想定しているのではないでしょうか。

最初、バグかなと思ってしまったので追記して頂けると助かります。
(間違っていたらすいません。)

よろしくお願いします。

**Comment by pasberth** [comment]
はい。気づいていたのですが更新が面倒だったので放置してました。

更新してみました。

**Comment by yonchu** [comment]
ですよね。
dotfiles覗いて、そうかなとは思ってました。

更新確認しました。
