### ISSUE TITLE
移動先のディレクトリ名にスペースが含まれているとエラーになる

### ISSUE THREAD

**Issue by yonchu** [pasberth/promptway#3]
`cd hoge¥ fuga` のようなスペースが含まれているディレクトリへ移動すると以下のエラーが発生します。

```
promptway:[:45: too many arguments
```

promptway.zshのL48付近の`$PWD`がダブルコーテーションで囲まれていないのが原因かと思います。

```
if [ -L $PWD ]; then  # <- ここ
  zformat -f _wd "$_wdsymfmt" a:"$A"
else
  zformat -f _wd "$_wdfmt" a:"$A"
fi
```

よろしくお願いします。

**Comment by pasberth** [comment]
ぼくの環境ではその現象は起こらないみたいなので、よければ直してパッチをくださいな

**Comment by yonchu** [comment]
`setopt sh_word_split`の影響でした。
このオプションを設定していると、単語分割がbash準拠になります。
zshでは、このオプションがオフの場合、クォートしなくても単語分割がおきないのでした。
(デフォルトではオフ)

ちょっと扱いが微妙ですね。
source したzshスクリプトだと設定によって影響が出てしまうので。

**Comment by pasberth** [comment]
対応しました〜

**Comment by yonchu** [comment]
確認しました。
ありがとうございます。
