### ISSUE TITLE
特定のディレクトリ間移動時にパスがおかしくなる

### ISSUE THREAD

**Issue by yonchu** [pasberth/promptway#4]
環境
- Mac 
- zsh 5.0.2

再現方法

`setopt auto_pushd` を設定した状態で、以下のようなディレクトリ移動を行う

``` console
$ mkdir hoge hog

$ cd hoge
$ cd ../hog   # 表示パス: ~/path/to/hog/~/path/to/hoge

$ cd ../hoge   # 表示パス: ~/path/to/hoge/hog/~/path/to/hoge
```

ディレクトリ名が `hoge` と `hog` のように一方の名前がもう一方の名前に前方一致する場合にこのような現象が起こるようです。

`hoge1` と ``hoge2` のような場合には起こりません。

また、先に述べたとおり `setopt auto_pushd` を設定している場合にのみ起こるようです。

ご確認お願いします。

**Comment by yonchu** [comment]
promptway というより [pasberth/pathf](https://github.com/pasberth/pathf) の方に問題あるようです。

`pathf d` または `pathf D` がパスの削除ではなく、単純な Prefix削除 になっているので、promptway で使うにはよろしくないです。

pathf の101行目と113行目を以下のように修正することで対応できそうです。

``` sh
# L:101
elif [ "$A" = "${A##$DEL_PATH}" ]; then

# L:113
if [ "$A" = "${A##$DEL_PATH}" ]; then
```

↓

``` sh
# L:101
elif [ "$A" = "${A##${DEL_PATH%/}/}" ]; then

# L:113
if [ "$A" = "${A##${DEL_PATH%/}/}" ]; then

# もしかしたら、$A の末尾にも / を入れて判定した方が良いかも
```

ただ、pathf 的にこういう仕様でいいのか判断できないのと、
promptway の動作確認しか行なっていないので、似たような問題が残っているかもしれないので、ひとまず報告だけに留めておきます。

よろしくお願いします。

**Comment by pasberth** [comment]
報告ありがとうです。

pathf は promptway でしか使ってないのと、 もともと promptway で使うために作ったもので、
こっちでもこの変更で問題ない事を確認したのでこれで問題ないです。

よければ PR をくださいな〜

**Comment by yonchu** [comment]
了解です。
帰宅したらPR送りますね。

**Comment by yonchu** [comment]
修正確認がとれたので、こちらも Close します。
