### ISSUE TITLE
親切設計にしたい

### ISSUE THREAD

**Issue by yonchu** [pasberth/promptway#8]
promptway はもっと評価されるべき！

そこで、これを広めるためにも、いくつか細かい改善を行いたいです。
個別に issue を投げる前に、軽く意見を伺いたいなと思い立てました。

以下、改善したい点
- pathf を submodule として入れたい
  - `git clone --recursive` だけでインストールが完了するようにしたい
  - これを対応すると実装の変更も必要
- README の改善
  - Requirements に realpath/grealpath に関する記述が欲しい
  - `":prompt:way" formats` などのオプションの説明が欲しい
  - Installation の項目が欲しい (pathfの導入方法なども)
- realpath/grealpath について
  - 現状、コマンドがないとエラーになってしまうが、`_prompt_backward` を使用しなればこのコマンドはなくても問題ない？ので、コマンドがない場合は無視し、`source` 時のみチェックしてそこで警告メッセージをだすようにしたい。
  - `_prompt_backward` の有効/無効を切り替えるオプションを用意すれば、有効のときのみ警告メッセージを出すようにできる。

注文が多くてすいません。
良ければ、ご意見をお聞かせ下さい。(すぐにとは言いませんので

採用できそうなものがあれば、個別に issue を立てて頂けると助かります。

**Comment by pasberth** [comment]
いいと思います (たぶん)

ぼくは あんまりいろんな人に使ってもらいたいとは思ってない (自分で使えればいいし使いたい人は使えばいい) ので、積極的にそれをしようという気はないけど、まあ親切設計になっていて悪い事はないと思うし、 issue とか立ててくれれば対応するかもしれないし対応しないかもしれないし、 PR とか送ってくれればマージします！！ (丸投げ)

**Comment by yonchu** [comment]
分かりました。
では少しづつ対応していこうかなと思います。
またPRを送ろうと思うので、そのときはよろしくお願いします。:D

**Comment by yonchu** [comment]
README 改善は別に issue がありますし、他は対応できたので close しますね。

色々無理なお願いを聞いて頂きありがとうございます。:smile:
